version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/envs/organization"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "env:organization"

  - package-ecosystem: "terraform"
    directory: "/envs/apps"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "env:apps"

  - package-ecosystem: "terraform"
    directory: "/modules/host"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "module:host"

  - package-ecosystem: "terraform"
    directory: "/modules/stages/organization"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "module:stages"

  - package-ecosystem: "terraform"
    directory: "/modules/stages/projects"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "module:stages"

  - package-ecosystem: "terraform"
    directory: "/modules/stages/network-hub"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "module:stages"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "edwinkassier"
    labels:
      - "dependencies"
      - "github-actions"
